name: Gedit Autosave Integration Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 0" # Weekly run to catch regressions

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            containerfile: Containerfile.latest.ubuntu
          - os: ubuntu-rolling
            containerfile: Containerfile.rolling.ubuntu
          - os: fedora-latest
            containerfile: Containerfile.fedora

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build container
        run: |
          docker build -t gedit-focus-autosave:${{ matrix.os }} -f .github/workflows/${{ matrix.containerfile }} .

      - name: Run integration test
        run: |
          docker run gedit-focus-autosave:${{ matrix.os }}